apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.ServiceName}}-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: {{.ServiceName}}-redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
